### ISSUE TITLE
Bryson-Ho 156 error

### ISSUE THREAD

**Issue by IanGowen** [danielrherber/dt-qp-project#5]
When trying to run Bryson-Ho 156, the program runs, but before it can plot anything, you get an error using BrysonHo156_plot saying there are "too many input arguments". This error occurs when you copy the code from GitHub as well as just opening it up from your computer. 
<img width="292" alt="Screenshot 2023-06-14 162129" src="https://github.com/danielrherber/dt-qp-project/assets/123217860/5d0221f7-a47a-4eda-a72f-dd9eb59ab7e9">

**Comment by danielrherber** [comment]
Line in BrysonHo156_plot:
https://github.com/danielrherber/dt-qp-project/blob/ad43dfb6b58e147be996e145c70af86fcf64f818/examples/linear-quadratic/bryson-ho-156/BrysonHo156_plot.m#L10

Line in BrysonHo156:
https://github.com/danielrherber/dt-qp-project/blob/ad43dfb6b58e147be996e145c70af86fcf64f818/examples/linear-quadratic/bryson-ho-156/BrysonHo156.m#L62

**Comment by danielrherber** [comment]
@IanGowen I am not seeing this error when running BrysonHo156 using the most recent commit. Can you upload your version of BrysonHo156 here?

**Comment by IanGowen** [comment]
Yes
`%--------------------------------------------------------------------------
% BrysonHo156.m
% p. 156 of A. E. Bryson Jr. and Y.-C. Ho, Applied Optimal Control.
% Taylor & Francis, 1975, isbn: 9780891162285
%--------------------------------------------------------------------------
%
%--------------------------------------------------------------------------
% Primary contributor: Daniel R. Herber (danielrherber on GitHub)
% Link: https://github.com/danielrherber/dt-qp-project
%--------------------------------------------------------------------------
function varargout = BrysonHo156(varargin)
% input arguments can be provided in the format 'BrysonHo156(auxdata,opts)'

% set local functions
ex_opts = @BrysonHo156_opts; % options function
ex_output = @BrysonHo156_output; % output function
ex_plot = @BrysonHo156_plot; % plot function

% set auxdata and opts (see local_opts)
[auxdata,opts] = DTQP_standardizedinputs(ex_opts,varargin);

%% tunable parameters
t0 = 0; tf = 10; % time horizon
auxdata.x0 = 10; auxdata.v0 = 1; auxdata.c = 1;
auxdata.omega = 1;

%% setup
% system dynamics
A = [0,1;-auxdata.omega^2,0];
B = [0;1];

% Lagrange term
L(1).left = 1; % control variables
L(1).right = 1; % control variables
L(1).matrix = 1/2; % 1/2*u^2

% Mayer term
M(1).left = 5; % final state variables
M(1).right = 5; % final state variables
M(1).matrix = [auxdata.c/2,0;0,0];

% initial conditions
LB(1).right = 4; % initial states
LB(1).matrix = [auxdata.x0;auxdata.v0];
UB(1).right = 4; % initial states
UB(1).matrix = [auxdata.x0;auxdata.v0];

% combine
setup.A = A; setup.B = B; setup.L = L; setup.M = M;
setup.LB = LB; setup.UB = UB; setup.t0 = t0; setup.tf = tf; setup.auxdata = auxdata;

%% solve
[T,U,Y,P,F,in,opts] = DTQP_solve(setup,opts);

%% output
[O,sol] = ex_output(T,U,Y,P,F,in,opts);
if nargout == 1
	varargout{1} = O;
end

%% plot
ex_plot(T,U,Y,P,F,in,opts,sol)

end
% User options function for this example
function opts = BrysonHo156_opts
% test number
num = 2;

switch num
case 1
    % default parameters
    opts = [];
case 2
    opts.dt.defects = 'HS';
    opts.dt.quadrature = 'CQHS';
    opts.dt.mesh = 'ED';
    opts.dt.nt = 5;
    opts.solver.tolerance = 1e-15;
    opts.solver.maxiters = 200;
    opts.solver.display = 'none';
    opts.dt.meshr.method = 'SS-BETTS';
    opts.dt.meshr.tolerance = 1e-8;
end

end`

**Comment by IanGowen** [comment]
Heres the code for the plot:
`%--------------------------------------------------------------------------
% BrysonHo156_plot.m
% Plot function for BrysonHo156 example
%--------------------------------------------------------------------------
%
%--------------------------------------------------------------------------
% Primary contributor: Daniel R. Herber (danielrherber on GitHub)
% Link: https://github.com/danielrherber/dt-qp-project
%--------------------------------------------------------------------------
function BrysonHo156_plot(in,opts)

if opts.general.plotflag

% preliminary plot options
flag = 'preliminary'; DTQP_plotCommon %#ok<NASGU>

%% state
figure('Color',wcolor); hold on

% plot state
solutionflag = true; %#ok<NASGU>
flag = 'plot-state'; DTQP_plotCommon %#ok<NASGU>

% configure axis
flag = 'axis'; DTQP_plotCommon %#ok<NASGU>

% save
figname = 'figure-state'; pathplots = msavename(mfilename('fullpath'),'plots'); %#ok<NASGU>
flag = 'save'; DTQP_plotCommon %#ok<NASGU>

%% control
figure('Color',wcolor); hold on

% plot control
solutionflag = true; %#ok<NASGU>
flag = 'plot-control'; DTQP_plotCommon %#ok<NASGU>

% configure axis
flag = 'axis'; DTQP_plotCommon %#ok<NASGU>

% save
figname = 'figure-control'; pathplots = msavename(mfilename('fullpath'),'plots'); %#ok<NASGU>
flag = 'save'; DTQP_plotCommon %#ok<NASGU>

%% error
figure('Color',wcolor); hold on

% plot error
flag = 'plot-error'; DTQP_plotCommon %#ok<NASGU>

% configure axis
flag = 'axis'; DTQP_plotCommon %#ok<NASGU>

% save
figname = 'figure-error'; pathplots = msavename(mfilename('fullpath'),'plots'); %#ok<NASGU>
flag = 'save'; DTQP_plotCommon %#ok<NASGU>

%% mesh refinement
if isfield(in,'meshr')

    % step size plot
    DTQP_MESH_plotStepsize(in.meshr.T)

    % mesh error plot
    DTQP_MESH_plotError(in.meshr.T,in.meshr.errors,in.meshr.tol)

end

end`

**Comment by danielrherber** [comment]
Perhaps your BrysonHo156_plot function was modified from the current one on GitHub:
https://github.com/danielrherber/dt-qp-project/blob/ad43dfb6b58e147be996e145c70af86fcf64f818/examples/linear-quadratic/bryson-ho-156/BrysonHo156_plot.m#L10

Note that the provided function has only 2 arguments rather than the full set `T,U,Y,P,F,in,opts,sol` shown above.

**Comment by IanGowen** [comment]
Ok I modified the code, but Im still getting the same error. Here's the updated plot code:
`%--------------------------------------------------------------------------
% BrysonHo156_plot.m
% Plot function for BrysonHo156 example
%--------------------------------------------------------------------------
%
%--------------------------------------------------------------------------
% Primary contributor: Daniel R. Herber (danielrherber on GitHub)
% Link: https://github.com/danielrherber/dt-qp-project
%--------------------------------------------------------------------------
function BrysonHo156_plot(T,U,Y,P,F,in,opts)

if opts.general.plotflag

% preliminary plot options
flag = 'preliminary'; DTQP_plotCommon %#ok<NASGU>

%% state
figure('Color',wcolor); hold on

% plot state
solutionflag = true; %#ok<NASGU>
flag = 'plot-state'; DTQP_plotCommon %#ok<NASGU>

% configure axis
flag = 'axis'; DTQP_plotCommon %#ok<NASGU>

% save
figname = 'figure-state'; pathplots = msavename(mfilename('fullpath'),'plots'); %#ok<NASGU>
flag = 'save'; DTQP_plotCommon %#ok<NASGU>

%% control
figure('Color',wcolor); hold on

% plot control
solutionflag = true; %#ok<NASGU>
flag = 'plot-control'; DTQP_plotCommon %#ok<NASGU>

% configure axis
flag = 'axis'; DTQP_plotCommon %#ok<NASGU>

% save
figname = 'figure-control'; pathplots = msavename(mfilename('fullpath'),'plots'); %#ok<NASGU>
flag = 'save'; DTQP_plotCommon %#ok<NASGU>

%% error
figure('Color',wcolor); hold on

% plot error
flag = 'plot-error'; DTQP_plotCommon %#ok<NASGU>

% configure axis
flag = 'axis'; DTQP_plotCommon %#ok<NASGU>

% save
figname = 'figure-error'; pathplots = msavename(mfilename('fullpath'),'plots'); %#ok<NASGU>
flag = 'save'; DTQP_plotCommon %#ok<NASGU>

%% mesh refinement
if isfield(in,'meshr')

    % step size plot
    DTQP_MESH_plotStepsize(in.meshr.T)

    % mesh error plot
    DTQP_MESH_plotError(in.meshr.T,in.meshr.errors,in.meshr.tol)

end

end`

**Comment by IanGowen** [comment]
Adding "sol" in BrysonHo_156 fixed the issue.
